//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the xMvvm Unity 3D toolchain.
//     Runtime Version: TBD
//     Created: 03/17/2020 17:03:34
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All

namespace EtAlii.xMvvm
{
    using UnityEngine;
    using System;
    using EtAlii.xMvvm.XamlVariant1;

    public partial class CompositionView : EtAlii.xMvvm.XamlVariant1.View<CompositionViewModel>  
    {
    }
}
