//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the xMvvm Unity 3D toolchain.
//     Runtime Version: 1.0.0-Preview
//     Created: 03/19/2020 21:42:35
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All

namespace EtAlii.xMvvm
{
    using UnityEngine;
    using System;
    using EtAlii.xMvvm.XamlVariant1;

    public partial class CompositionView : EtAlii.xMvvm.XamlVariant1.View<CompositionViewModel>  
    {
        // Resources.
        private readonly LinearTransformationConverter _linearTransformationConverter;
        
        // Component bindings.
        private readonly Binding<UnityEngine.UI.Slider, CompositionViewModel> _up;
        private readonly Binding<UnityEngine.UI.Slider, CompositionViewModel> _forward;
        private readonly Binding<UnityEngine.UI.Toggle, CompositionViewModel> _rotate;

        // Element bindings.
        private readonly EtAlii.xMvvm.XamlVariant1.ElementBinding _canvas;
        private readonly EtAlii.xMvvm.XamlVariant1.ElementBinding _subject;
        private readonly EtAlii.xMvvm.XamlVariant1.ElementBinding _child;
        private readonly EtAlii.xMvvm.XamlVariant1.ElementBinding _child3;
        private readonly EtAlii.xMvvm.XamlVariant1.ElementBinding _child4;
        private readonly EtAlii.xMvvm.XamlVariant1.ElementBinding _child2;
        private readonly EtAlii.xMvvm.XamlVariant1.ElementBinding _photo;
        private readonly EtAlii.xMvvm.XamlVariant1.ElementBinding _child5;

        public CompositionView() : this(GameObject.Instantiate(Resources.Load("CompositionView.prefab", typeof(GameObject))) as GameObject)
        {
        }
        
        public CompositionView(GameObject gameObject) : base(gameObject)
        {
            // Setup the resources.
            _linearTransformationConverter = new LinearTransformationConverter();

            // Wire the component bindings.
            _up = new PropertyBinding<UnityEngine.UI.Slider, CompositionViewModel>(this, "Canvas/Panel/UpSlider", component => component.value, vm => vm.Up, BindingMode.OneWayToSource);
            _forward = new PropertyBinding<UnityEngine.UI.Slider, CompositionViewModel>(this, "Canvas/Panel/ForwardSlider", component => component.value, vm => vm.Forward, BindingMode.OneWayToSource);
            _rotate = new PropertyBinding<UnityEngine.UI.Toggle, CompositionViewModel>(this, "Canvas/Panel/RotateToggle", component => component.isOn, vm => vm.Rotate, BindingMode.OneWayToSource);

            // Setup the element bindings.
            var element1 = ﻿new EtAlii.xMvvm.XamlVariant1.ElementBinding("Child8");
            var element2 = ﻿new EtAlii.xMvvm.XamlVariant1.ElementBinding("Child6");
            _child5 = ﻿new EtAlii.xMvvm.XamlVariant1.ElementBinding(gameObject, "Child5", new EtAlii.xMvvm.XamlVariant1.ElementBinding[] { element2, element1 });
            _photo = ﻿new EtAlii.xMvvm.XamlVariant1.ElementBinding(gameObject, "Photo");
            _child2 = ﻿new EtAlii.xMvvm.XamlVariant1.ElementBinding("Child2");
            _child4 = ﻿new EtAlii.xMvvm.XamlVariant1.ElementBinding("Child4");
            _child3 = ﻿new EtAlii.xMvvm.XamlVariant1.ElementBinding("Child3");
            _child = ﻿new EtAlii.xMvvm.XamlVariant1.ElementBinding("Child", new EtAlii.xMvvm.XamlVariant1.ElementBinding[] { _child3, _child4 });
            _subject = ﻿new EtAlii.xMvvm.XamlVariant1.ElementBinding(gameObject, "Subject", new EtAlii.xMvvm.XamlVariant1.ElementBinding[] { _child, _child2 });
            _canvas = ﻿new EtAlii.xMvvm.XamlVariant1.ElementBinding(gameObject, "Canvas2");
 
            // And initialize.
            Initialize();   
        }

    }
}
