//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the xMvvm Unity 3D toolchain.
//     Runtime Version: 1.0.0-Preview
//     Created: 03/31/2020 23:09:31
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All

namespace EtAlii.xMvvm
{
    using UnityEngine;
    using System;
    using EtAlii.xMvvm.XamlVariant1;

    public partial class LocationsView : EtAlii.xMvvm.XamlVariant1.View<LocationsViewModel>  
    {
        // Resources.
        
        // Component bindings.

        // Element bindings.
        private readonly EtAlii.xMvvm.XamlVariant1.ElementBinding<LocationsViewModel> _locations;

        public LocationsView() : this(GameObject.Instantiate(Resources.Load("LocationsView.prefab", typeof(GameObject))) as GameObject)
        {
        }
        
        public LocationsView(GameObject gameObject) : base(gameObject)
        {
            // Setup the resources.

            // Setup the component bindings.

            // Setup the element bindings.
            _locations = ﻿new EtAlii.xMvvm.XamlVariant1.ListElementBinding<LocationsViewModel>(this, "Globe/Locations", vm => vm.Locations);
 
            // And initialize.
            Initialize();   
        }
    }
}
