//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the xMvvm Unity 3D toolchain.
//     Runtime Version: 1.0.0-Preview
//     Created: 03/30/2020 20:56:45
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// ReSharper disable All

namespace EtAlii.xMvvm
{
    using UnityEngine;
    using System;
    using EtAlii.xMvvm.XamlVariant1;

    public partial class LocationsView : EtAlii.xMvvm.XamlVariant1.View<LocationsViewModel>  
    {
        // Resources.
        
        // Component bindings.

        // Element bindings.
        private readonly EtAlii.xMvvm.XamlVariant1.ElementBinding<LocationsViewModel> _canvas;
        private readonly EtAlii.xMvvm.XamlVariant1.ElementBinding<LocationsViewModel> _subject;
        private readonly EtAlii.xMvvm.XamlVariant1.ElementBinding<LocationsViewModel> _child;
        private readonly EtAlii.xMvvm.XamlVariant1.ElementBinding<LocationsViewModel> _child3;
        private readonly EtAlii.xMvvm.XamlVariant1.ElementBinding<LocationsViewModel> _child4;
        private readonly EtAlii.xMvvm.XamlVariant1.ElementBinding<LocationsViewModel> _child2;
        private readonly EtAlii.xMvvm.XamlVariant1.ElementBinding<LocationsViewModel> _photo;
        private readonly EtAlii.xMvvm.XamlVariant1.ElementBinding<LocationsViewModel> _child5;

        public LocationsView() : this(GameObject.Instantiate(Resources.Load("LocationsView.prefab", typeof(GameObject))) as GameObject)
        {
        }
        
        public LocationsView(GameObject gameObject) : base(gameObject)
        {
            // Setup the resources.

            // Setup the component bindings.

            // Setup the element bindings.
            var element1 = ﻿new EtAlii.xMvvm.XamlVariant1.ElementBinding<LocationsViewModel>("Child8");
            var element2 = ﻿new EtAlii.xMvvm.XamlVariant1.ElementBinding<LocationsViewModel>("Child6");
            _child5 = ﻿new EtAlii.xMvvm.XamlVariant1.ElementBinding<LocationsViewModel>(this, "Child5", new EtAlii.xMvvm.XamlVariant1.ElementBinding<LocationsViewModel>[] { element2, element1 });
            _photo = ﻿new EtAlii.xMvvm.XamlVariant1.ElementBinding<LocationsViewModel>(this, "Photo");
            _child2 = ﻿new EtAlii.xMvvm.XamlVariant1.ElementBinding<LocationsViewModel>("Child2");
            _child4 = ﻿new EtAlii.xMvvm.XamlVariant1.ElementBinding<LocationsViewModel>("Child4");
            _child3 = ﻿new EtAlii.xMvvm.XamlVariant1.ElementBinding<LocationsViewModel>("Child3");
            _child = ﻿new EtAlii.xMvvm.XamlVariant1.ElementBinding<LocationsViewModel>("Child", new EtAlii.xMvvm.XamlVariant1.ElementBinding<LocationsViewModel>[] { _child3, _child4 });
            _subject = ﻿new EtAlii.xMvvm.XamlVariant1.ElementBinding<LocationsViewModel>(this, "Subject", element => element.transform, vm => vm.SubjectTransformation, new EtAlii.xMvvm.XamlVariant1.ElementBinding<LocationsViewModel>[] { _child, _child2 });
            _canvas = ﻿new EtAlii.xMvvm.XamlVariant1.ElementBinding<LocationsViewModel>(this, "Canvas2");
 
            // And initialize.
            Initialize();   
        }
    }
}
