//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the xMvvm Unity 3D toolchain.
//     Runtime Version: TBD
//     Created: 3/5/2020 8:16:31 PM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtAlii.xMvvm 
{
    using UnityEngine;
    using System;
    using EtAlii.xMvvm.XamlVariant1;

    public partial class LoginView : View<LoginViewModel>  
    {
        private readonly Binding<TMPro.TMP_InputField, LoginViewModel> _password;
        private readonly Binding<TMPro.TMP_InputField, LoginViewModel> _userName;
        private readonly Binding<UnityEngine.UI.Button, LoginViewModel> _login;
        private readonly Binding<UnityEngine.UI.Button, LoginViewModel> _cancel;
        private readonly Binding<UnityEngine.UI.Button, LoginViewModel> _toggleLoginButton;
        private readonly Binding<UnityEngine.UI.Button, LoginViewModel> _toggleCancelButton;
         
        public LoginView() : this(GameObject.Instantiate(Resources.Load("LoginView.prefab", typeof(GameObject))) as GameObject)
        {
        }
        
        public LoginView(GameObject gameObject) : base(gameObject)
        {
            // Wire the bindings.
            _password = new PropertyBinding<TMPro.TMP_InputField, LoginViewModel>(this, "Canvas/Panel/PasswordTextBox", component => component.text, vm => vm.Password, BindingMode.TwoWay);
            _userName = new PropertyBinding<TMPro.TMP_InputField, LoginViewModel>(this, "Canvas/Panel/UserNameTextBox", component => component.text, vm => vm.UserName, BindingMode.TwoWay);
            _login = new EventBinding<UnityEngine.UI.Button, LoginViewModel>(this, "Canvas/Panel/LoginButton", component => component.onClick, vm => vm.OnLogin);
            _cancel = new EventBinding<UnityEngine.UI.Button, LoginViewModel>(this, "Canvas/Panel/CancelButton", component => component.onClick, vm => vm.OnCancel);
            _toggleLoginButton = new PropertyBinding<UnityEngine.UI.Button, LoginViewModel>(this, "Canvas/Panel/LoginButton", component => component.interactable, vm => vm.IsValid, BindingMode.OneWay);
            _toggleCancelButton = new PropertyBinding<UnityEngine.UI.Button, LoginViewModel>(this, "Canvas/Panel/CancelButton", component => component.interactable, vm => vm.IsValid, BindingMode.OneWay);

            // And initialize.
            Initialize();   
        }
    }
}
