//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the xMvvm toolset.
//     Runtime Version:
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtAlii.xMvvm 
{
    using UnityEngine;
    using System;
    
    public partial class LoginView3 : MonoBehaviour 
    {
    }
}
