//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the xMvvm Unity 3D toolchain.
//     Runtime Version: TBD
//     Created: 3/3/2020 2:49:38 PM
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtAlii.xMvvm 
{
    using UnityEngine;
    using System;

    public partial class LoginView : EtAlii.xMvvm.XamlVariant1.View  
    {
        /// <summary>
        /// The LoginViewModel that should be used to power the view.     
        /// </summary>
        public LoginViewModel ViewModel { get; set; }
        
        public GameObject GameObject {get;}

        private readonly EtAlii.xMvvm.XamlVariant1.Binding<TMPro.TMP_InputField, LoginViewModel> _password;
        private readonly EtAlii.xMvvm.XamlVariant1.Binding<TMPro.TMP_InputField, LoginViewModel> _userName;
         
        public LoginView()
            : this(GameObject.Instantiate(Resources.Load("LoginView.prefab", typeof(GameObject))) as GameObject)
        {
        }
        
        public LoginView(GameObject gameObject)
        {
            // Setup a prefab instance. 
            GameObject = gameObject;
            
            // Wire the bindings.
            _password = new EtAlii.xMvvm.XamlVariant1.Binding<TMPro.TMP_InputField, LoginViewModel>("Canvas/Panel/PasswordTextBox", component => component.text, vm => "vm.x:Bind Password Mode=TwoWay");
            _userName = new EtAlii.xMvvm.XamlVariant1.Binding<TMPro.TMP_InputField, LoginViewModel>("Canvas/Panel/UserNameTextBox", component => component.text, vm => "vm.x:Bind UserName Mode=TwoWay");
                
            // And initialize.
            Initialize();   
        }
    }
}
